Table users {
  id integer [pk]
  email text [not null, unique]
  name text [not null]
  status text [not null]
  created_at text [not null, default: `now()`]
  is_sync integer [not null, default: 1]
  is_deleted integer [not null, default: 0]
  is_new integer [not null, default: 1]
}

Table boards {
  id integer [pk]
  title text [not null]
  description text
  is_private integer [not null, default: 0]
  created_at text [not null, default: `now()`]
  updated_at text [not null, default: `now()`]
  is_sync integer [not null, default: 1]
  is_deleted integer [not null, default: 0]
  is_new integer [not null, default: 1]
}

Table statuses {
  id integer [pk]
  board_id integer [not null]
  name text(50) [not null]
  position integer [not null, default: 0]
  is_sync integer [not null, default: 1]
  is_deleted integer [not null, default: 0]
  is_new integer [not null, default: 1]

  indexes {
    (board_id, name) [unique]
  }
}

Table tasks {
  id integer [pk]
  board_id integer [not null]
  title text [not null]
  description text
  status_id integer [not null]
  priority_color text(50) [not null]
  deadline text
  created_at text [not null, default: `now()`]
  updated_at text [not null, default: `now()`]
  is_sync integer [not null, default: 1]
  is_deleted integer [not null, default: 0]
  is_new integer [not null, default: 1]
}

Ref: statuses.board_id > boards.id [delete: cascade]
Ref: tasks.board_id > boards.id [delete: cascade]
Ref: tasks.status_id > statuses.id [delete: cascade]
